baseurl: '/'
permalink: pretty
title: 'Necessio Wellness Community'

# logo:
#   mobile: "images/logo/logo-mobile.svg"
#   mobile_height: "32px"
#   mobile_width: "32px"
#   desktop: "images/logo/logo.svg"
#   desktop_height: "32px"
#   desktop_width: "120px"

logo:
  mobile: "images/logo/logo.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.png"
  desktop_height: "32px"
  desktop_width: "120px"


home: 
  limit_programs: 6

collections:
  programs:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "programs"
    values:
      layout: "program"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
